### ISSUE TITLE
Dispose all... (possibly scoped to the current view model)

### ISSUE THREAD

**Issue by mttmccb** [aurelia/event-aggregator#21]
I'm curious if there is a way to dispose all subscriptions?

Currently I'm storing a reference to them all and then disposing them individually but it would be nice there were an option to dispose them all, perhaps scoped to the current view model. so the deactivate method becomes something like

```
deactivate() {
  this.ea.disposeAll();
}
```

rather than 

```
deactivate() {
  this.event1.dispose();
  this.event2.dispose();
  this.event3.dispose();
  this.event4.dispose();
  this.event5.dispose();
  this.event6.dispose();
}
```

(I know I could store all the events in an array  and dispose them with a looping helper class but that feels like I'm doing the EventAggregators job :P)

**Comment by EisenbergEffect** [comment]
There's no api for that because the EA is typically global, What you may want to do is create your own EA that wraps ours and records what subscriptions are made. Then give it a disposeAll method to loop over them. You can even have our EA injected into yours. Then register yours as transient so that each VM gets its own instance. That should do the trick.

**Comment by mttmccb** [comment]
Good plan, that would work.
